name: Build and Deploy Go to Azure Functions

on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                - info
                - warning
                - debug
    push:
        branches:
            - main
        paths:
            - 'api/*'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.2'

    - name: Build the Go project
      run: |
        cd api
        go build .
        ls
    
    - name: Azure login
      uses: azure/login@v2
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: Deploy to Azure Functions
      run: |
        ls
        cd api
        func azure functionapp publish func-pscv-prod-eun-001

