name: Build and Deploy Go to Azure Functions

on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                - info
                - warning
                - debug
    push:
        branches:
            - main
        paths:
            - 'api/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.2'

    - name: Build the Go project
      run: |
        cd api
        env GOOS=windows go build .

    - name: Archive the build output
      run: |
        zip function.zip .

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: 'fa-pscv-prod-ne-001'
        package: './api/function.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
