name: Deploy PSCV resources
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - main
    paths:
      - infra 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/bicep-deploy@v1
      with:
        type: deploymentStack
        operation: create
        scope: subscription
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
        location: northeurope
        name: deploy-pscv-resources
        template-file: ./infra/main.bicep
        parameters: '{"repositoryToken": ${{ secrets.REPO_TOKEN }}, "buildPipelineApiLocation": "api"}'
        action-on-unmanage-resources: delete
        action-on-unmanage-resourcegroups: delete
        deny-settings-mode: none